server:
  port: 8088
spring:
  application:
    name: ${HOSTNAME:@osaas@}${PID}
  profiles:
    active: prod
  jackson:
    default-property-inclusion: ALWAYS

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
    url: jdbc:h2:./data/osaas;MODE=MYSQL
    hikari:
      max-lifetime: 120000
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console
      enabled: true
