server:
  port: ${random.int[10000,19999]}
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
    url: jdbc:h2:./data/hertzbeat-test;MODE=MYSQL
    hikari:
      max-lifetime: 120000
  jpa:
    hibernate:
      ddl-auto: update
